##
# @File: ResourceRequest.srv
#
# @brief
# Used to ask the Resource Manager for resources.
#
# @behavior_id
# The ID of the behavior that is requesting resources.
#
# @priority
# The priority of the behavior.
#
# @info
# YAML or JSON formatted string of Behavior level information
# needed for the Resource Manager to calculate scores.
#
# @roles
# List of all the resources the behavior needs and why.
#
# @success
# Indicating if the allocation of resources was successful
##

string behavior_id
uint8  priority
string info
architecture_msgs/Role[] roles

---

bool success
architecture_msgs/Role[] roles

## ResourceRequest.srv ##
